### ISSUE TITLE
Set amount to mint

### ISSUE THREAD

**Issue by isp** [SolanaNFTHolder/MagicEden-minting-bot#1]
Is there way to define how many you want to mint or does it default to a single mint as opposed to max?

**Comment by NOTSUREBRO** [comment]
GIVE ME MY SOL PLS DUDE. U HAVE A CREW OF PEOPLE OR WHAT? SHEESH. JUST GIVE ME MY 3.9 SOL AND ILL LEAVE U ALONE DUDE. I LITERALLY HAVE NOTHING. I HAVE NO DIPLOMA, NO JOB. NOTHING. PLS.
