### ISSUE TITLE
Success

### ISSUE THREAD

**Issue by FijiMlk** [SolanaNFTHolder/MagicEden-minting-bot#24]
![image](https://user-images.githubusercontent.com/97924753/172121603-db673cf3-5147-498a-98fb-12dc480a47c1.png)

### AVE free bot)

**Comment by givememysol** [comment]
give me my sol pls. i dont understand why u r so selfish. is that how you think aswell when you see a beggar on the street? this is not right. pls man. i have nothing. i just need my money back. that is the last of my money.... 

AsMTKMA1iGMYTQjH27QzmptrTyt5k5cSfMMdSsp2ceWA
